name: stepway
description: Flutter Fest Hackathon

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_sliders: ^19.4.50
  syncfusion_flutter_core: ^19.4.50

  # Introduction Screen
  introduction_screen: ^2.1.0
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  flutter_native_splash: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/stepway.png
  fullscreen: true
